### ISSUE TITLE
Script not work on Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by Raxone** [brendaningram/linux-audio-setup-scripts#5]
Script not work on Ubuntu 22.04.3 LTS.
Fresh install Ubuntu 22.04.3 LTS.
When install pipewire if no audio interface on system DBUS error stop install script.

**Comment by edrickblade** [comment]
> Script not work on Ubuntu 22.04.3 LTS. Fresh install Ubuntu 22.04.3 LTS. When install pipewire if no audio interface on system DBUS error stop install script.
What I'm doing is to open the scripts in gedit and updated with the new links etc. and install everything manual(copy and paste each line of the script) I think @brendaningram had taken some vacations because requested an update to the scripts with no answers, lets give Him some time to see what me develop in 2024.
